CREATE TABLE roles (
    role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    username VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(100)
);

CREATE TABLE user_roles (
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

/*CREATE TABLE friendship (
    friendship_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    recipient_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT chk_friendship_not_self CHECK (requester_id <> recipient_id),
    CONSTRAINT chk_friendship_status CHECK (status IN ('PENDING', 'ACCEPTED'))
);*/

CREATE TABLE friendship (
                            friendship_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            requester_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
                            recipient_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
                            status VARCHAR(20) NOT NULL,
                            CONSTRAINT chk_friendship_order CHECK (requester_id <> recipient_id),
                            CONSTRAINT chk_friendship_status CHECK (status IN ('PENDING', 'ACCEPTED'))
);

CREATE UNIQUE INDEX uk_friendship_pair
    ON friendship (requester_id, recipient_id);

/*
CREATE UNIQUE INDEX uk_friendship_pair
    ON friendship (LEAST(requester_id, recipient_id), GREATEST(requester_id, recipient_id));
*/

CREATE TABLE chat (
    chat_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INTEGER NOT NULL REFERENCES users(user_id)
);

CREATE TABLE chat_users (
    chat_id INTEGER NOT NULL REFERENCES chat(chat_id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    PRIMARY KEY (chat_id, user_id)
);

CREATE TABLE message (
    message_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id INTEGER NOT NULL REFERENCES chat(chat_id) ON DELETE CASCADE,
    sender_user_id INTEGER NOT NULL REFERENCES users(user_id),
    content VARCHAR(4000) NOT NULL,
    sent_at TIMESTAMP NOT NULL,
    last_edit TIMESTAMP
);

CREATE INDEX idx_message_chat_sent_at ON message (chat_id, sent_at);
